kylin-assistant/translations/*_bo_CN.qm usr/share/kylin-assistant/translations 
kylin-ipmsg/translations/*_bo_CN.qm usr/share/kylin-ipmsg/translations
kylin-video/translations/*_bo_CN.qm usr/share/kylin-video/translations
ukui-biometric-manager/translations/*_bo_CN.qm usr/share/ukui-biometric-manager/translations
yhkylin-backup-tools/translations/*_bo_CN.qm usr/share/yhkylin-backup-tools/translations
